### ISSUE TITLE
TST: add tests

### ISSUE THREAD

**Issue by mdhaber** [mdhaber/marray#3]
There are no tests. Add property-based tests using Hypothesis for all features.

**Comment by lucascolley** [comment]
What do you think about testing with array-api-strict? Works well for me in array-api-extra

**Comment by mdhaber** [comment]
Oh, this is closed. https://github.com/mdhaber/marray/blob/main/marray/tests/test_marray.py tests for all dtypes with both NumPy and array-api-strict.

**Comment by lucascolley** [comment]
Ah cool - you may want to add array-api-strict as an optional dependency in pyproject.toml

**Comment by mdhaber** [comment]
Ah, yes, thanks.
