### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mdhaber** [mdhaber/marray#38]
I'd be happy to use this if it is OK with the NumPy folks.

<img src="https://github.com/user-attachments/assets/1b21c8a3-838c-4db3-b8a8-86856b1b267a" width=200>

I've always liked the NumPy logo, and I think it fits with the theme that this library just wraps the behavior of the underlying array.

@seberg Do you think that would be alright?

**Comment by seberg** [comment]
If you have time, maybe something for the community meeting next week?

**Comment by mdhaber** [comment]
Discussed this at the community meeting on 12/18, and others were OK with it as long as it was clear that the project is not NumPy. I added a footnote at the bottom of `README.md` and the documentation main page to make this obvious:

> The MArray logo is a nod to NumPy, but MArray is not affiliated with the NumPy project.
