### ISSUE TITLE
`__array_namespace__()` magic methods

### ISSUE THREAD

**Issue by lucascolley** [mdhaber/marray#59]
See https://github.com/mdhaber/marray/issues/6#issuecomment-2564555360 - I think methods like `__name__` and `__repr__` should be modified based on the array-backend's namespace.

**Comment by mdhaber** [comment]
Changing `__name__` sounds good. I'm not sure if it's needed for `repr` though. `repr` output is only executable if the proper imports are made, and there's no guarantee even that the things that would need to be imported are public (e.g. `strict.Array`). Two different array backend stays can certainly have the same `repr`, too. Why change it?

**Comment by lucascolley** [comment]
I mean the repr of the module. Right now `repr(marray.get_namespace(np).arange(2).__array_namespace__())` is `"<module 'mxp'>"` - that isn't executable, so I think we are talking about different things?

**Comment by mdhaber** [comment]
Ah, yes. I thought you meant the `repr` of an array.

**Comment by lucascolley** [comment]
It would be interesting to try pushing `marray` through SciPy's test suite, to find out whether we care more about whether it is an `marray` or what the underlying backend is. I guess the safe answer is that we may care about both.

**Comment by mdhaber** [comment]
Yeah, I planned to test it with the array API compatible stats functions.

**Comment by mdhaber** [comment]
Re: https://github.com/mdhaber/marray/issues/59#issuecomment-2564570833, if you can create a branch that brings `marray` into SciPy as a submodule/subproject, I would be happy to try using it in some stats functions.
