### ISSUE TITLE
DOC: code output should render

### ISSUE THREAD

**Issue by mdhaber** [mdhaber/marray#62]
I thought that I had it working so that the output of code would render when the docs were built, but now:

![image](https://github.com/user-attachments/assets/0817085c-156c-478c-ac9f-118b1ee67c2d)

No output.

It's possible I'm mistaken, but perhaps it could have changed with the changes in gh-50?
Either way, would you be willing to take a look at this @lucascolley?

**Comment by lucascolley** [comment]
hmm, the exact same command `jupyter-book build mybook/` is used. Are you able to get the code output working in a local build?

**Comment by lucascolley** [comment]
https://jupyterbook.org/en/stable/file-types/myst-notebooks.html#code-cells seems to suggest using `{code-cell}` on cells

**Comment by lucascolley** [comment]
Is it possible that this changed when you moved the notebook to markdown, rather than the pixi pr?

**Comment by mdhaber** [comment]
Well, I got it to render locally, and it's executing the code online, but it can't find NumPy.

**Comment by lucascolley** [comment]
Yep, should just need to add the runtime deps to the docs feature
