### ISSUE TITLE
Can we fix whether `np.iterable` considers a 0-D MArray to be iterable?

### ISSUE THREAD

**Issue by mdhaber** [mdhaber/marray#72]
```python3
import numpy as np
import cupy as cp
from marray import numpy as mnp

np.iterable(np.asarray(1))  # False
np.iterable(cp.asarray(1))  # False
np.iterable(mnp.asarray(1))  # True
```
Fix this. Some SciPy functions will fail where NumPy passes because `np.iterable` is used to determine whether `args` need to be wrapped in a tuple.

**Comment by lucascolley** [comment]
Could a workaround be something like `np.iterable(x) and (not is_array_api_obj(x) or x.ndim >= 1)`? So arrays get an additional ndim check?

**Comment by mdhaber** [comment]
I was hoping we could look into how `np.iterable` works and fix it at the root. CuPy 0-d arrays are `False`, too, so it should be doable.
